#!/usr/bin/env python3
"""Independent CAN 2.0 reference encoder for tb_can.v: builds the exact
on-bus bitstream (SOF through EOF, stuffing and CRC-15 per ISO 11898-1)
for a few frames and writes them as a Verilog include (can_ref.vh)."""
import sys

def crc15(bits):
    crc = 0
    for b in bits:
        nxt = b ^ ((crc >> 14) & 1)
        crc = (crc << 1) & 0x7FFF
        if nxt:
            crc ^= 0x4599
    return crc

def frame_bits(ident, ext, dlc, data, rtr=False, corrupt_crc=False):
    bits = [0]  # SOF
    if ext:
        bits += [(ident >> (28 - i)) & 1 for i in range(11)]   # base ID
        bits += [1, 1]                                          # SRR, IDE
        bits += [(ident >> (17 - i)) & 1 for i in range(18)]   # ID extension
        bits += [1 if rtr else 0, 0, 0]                          # RTR, r1, r0
    else:
        bits += [(ident >> (10 - i)) & 1 for i in range(11)]
        bits += [1 if rtr else 0, 0, 0]                          # RTR, IDE, r0
    bits += [(dlc >> (3 - i)) & 1 for i in range(4)]
    if not rtr:
        for byte in data[:min(dlc, 8)]:
            bits += [(byte >> (7 - i)) & 1 for i in range(8)]
    crc = crc15(bits)
    if corrupt_crc:
        crc ^= 1
    bits += [(crc >> (14 - i)) & 1 for i in range(15)]
    # Stuff SOF..CRC.
    out, last, run = [], None, 0
    for b in bits:
        out.append(b)
        run = run + 1 if b == last else 1
        last = b
        if run == 5:
            out.append(1 - b)
            last, run = 1 - b, 1
    stuffed_len = len(out)
    out += [1]          # CRC delimiter
    out += [1]          # ACK slot as sent by the transmitter (recessive)
    out += [1] * 8      # ACK delimiter + EOF
    return out, stuffed_len

FRAMES = [
    # name,          id,          ext,   dlc, data,                                   rtr,   corrupt
    ("STD_123",      0x123,       False, 8, [0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88], False, False),
    ("EXT_1ABCDEF5", 0x1ABCDEF5,  True,  3, [0xA5,0x5A,0xFF],                         False, False),
    ("STD_000",      0x000,       False, 0, [],                                       False, False),
    ("EXT_RTR_1",    0x00000001,  True,  2, [],                                       True,  False),
    ("STD_555",      0x555,       False, 5, [0x00,0xFF,0x00,0xFF,0x0F],               False, False),
    ("STD_555_BAD",  0x555,       False, 5, [0x00,0xFF,0x00,0xFF,0x0F],               False, True),
]

with open(sys.argv[1] if len(sys.argv) > 1 else "can_ref.vh", "w") as f:
    f.write("// Generated by gen_can_ref.py - do not edit.\n")
    for idx, (name, ident, ext, dlc, data, rtr, bad) in enumerate(FRAMES):
        bits, slen = frame_bits(ident, ext, dlc, data, rtr, bad)
        f.write(f"localparam REF_{name} = {idx};\n")
    f.write("task load_refs;\n  begin\n")
    for idx, (name, ident, ext, dlc, data, rtr, bad) in enumerate(FRAMES):
        bits, slen = frame_bits(ident, ext, dlc, data, rtr, bad)
        s = "".join(str(b) for b in bits)
        f.write(f"    ref_len[{idx}] = {len(bits)}; ref_stuffed[{idx}] = {slen};\n")
        f.write(f"    ref_bits[{idx}] = {len(bits)}'b{s};\n")
    f.write("  end\nendtask\n")
