/* Regenerated by tools/build_bitstream.py before each synthesis run.
 * Checked-in defaults: 64KB internal SRAM, ~26.845MHz system clock
 * (27MHz oscillator through Gowin_rPLL_sys - see top.v). */
localparam SRAM_ADDR_WIDTH = 14;
localparam CLK_FREQ = 26845000;
