/* Top level SoC for the NanoTangArduino core (Sipeed Tang Nano 20K).
 *
 * Derived from grughuhler/picorv32_tang_nano_20k's top.v (BSD-2-Clause),
 * trimmed for v1 (LEDs + UART only, WS2812B/countdown timer dropped) and
 * extended with a free-running systick peripheral for millis()/micros().
 *
 * Memory map:
 *   0x0000_0000 - SRAM_BYTES-1   SRAM (program + data, size set by
 *                                 SRAM_ADDR_WIDTH, see sys_parameters.v)
 *   0x8000_0000                  LEDs (bits [5:0], read/write)
 *   0x8000_0008                  UART clock divisor register
 *   0x8000_000c                  UART data register
 *   0x8000_0020                  systick free-running counter (read-only)
 *   0x8000_0040                  I2S BCLK divisor register (write)
 *   0x8000_0044                  I2S data register: {left16,right16} (write)
 *   0x8000_0048                  I2S control register: bit0 = PA_EN (write)
 *
 * The picorv32 core has a very simple memory interface; see
 * https://github.com/YosysHQ/picorv32
 */

module top
  (
   input wire        clk,
   input wire        reset_button,
   input wire        uart_rx,
   output wire       uart_tx,
   output wire [5:0] leds,
   output wire       i2s_bclk,
   output wire       i2s_ws,
   output wire       i2s_din,
   output wire       i2s_pa_en
   );

   // Provides SRAM_ADDR_WIDTH and CLK_FREQ, regenerated by the build
   // pipeline (tools/build_bitstream.py) from the platform's board config.
   `include "sys_parameters.v"

   parameter        MEMBYTES = 4*(1 << SRAM_ADDR_WIDTH);
   parameter [31:0] STACKADDR = MEMBYTES; // Grows down; runtime sets it.
   parameter [31:0] PROGADDR_RESET = 32'h0000_0000;
   parameter [31:0] PROGADDR_IRQ = 32'h0000_0000;

   wire              reset_n;
   wire              mem_valid;
   wire              mem_instr;
   wire [31:0]       mem_addr;
   wire [31:0]       mem_wdata;
   wire [31:0]       mem_rdata;
   wire [3:0]        mem_wstrb;
   wire              mem_ready;

   wire              leds_sel;
   wire              leds_ready;
   wire [31:0]       leds_data_o;
   wire              sram_sel;
   wire              sram_ready;
   wire [31:0]       sram_data_o;
   wire              uart_sel;
   wire [31:0]       uart_data_o;
   wire              uart_ready;
   wire              systick_sel;
   wire              systick_ready;
   wire [31:0]       systick_data_o;
   wire              i2s_sel;
   wire              i2s_ready;

   assign sram_sel    = mem_valid && (mem_addr < MEMBYTES);
   assign leds_sel    = mem_valid && (mem_addr == 32'h8000_0000);
   assign uart_sel    = mem_valid && ((mem_addr & 32'hffff_fff8) == 32'h8000_0008);
   assign systick_sel = mem_valid && (mem_addr == 32'h8000_0020);
   assign i2s_sel     = mem_valid && ((mem_addr & 32'hffff_fff0) == 32'h8000_0040);

   assign mem_ready = mem_valid &
                       (sram_ready | leds_ready | uart_ready | systick_ready | i2s_ready);

   assign mem_rdata = sram_sel    ? sram_data_o :
                      leds_sel    ? leds_data_o :
                      uart_sel    ? uart_data_o :
                      systick_sel ? systick_data_o : 32'h0;

   assign leds = ~leds_data_o[5:0]; // Onboard LEDs are active-low.

   reset_control reset_controller
     (
      .clk(clk),
      .reset_button(reset_button),
      .reset_n(reset_n)
      );

   uart_wrap uart
     (
      .clk(clk),
      .reset_n(reset_n),
      .uart_tx(uart_tx),
      .uart_rx(uart_rx),
      .uart_sel(uart_sel),
      .addr(mem_addr[3:0]),
      .uart_wstrb(mem_wstrb),
      .uart_di(mem_wdata),
      .uart_do(uart_data_o),
      .uart_ready(uart_ready)
      );

   systick tick
     (
      .clk(clk),
      .reset_n(reset_n),
      .systick_sel(systick_sel),
      .systick_ready(systick_ready),
      .systick_data_o(systick_data_o)
      );

   i2s_tx i2s
     (
      .clk(clk),
      .reset_n(reset_n),
      .i2s_sel(i2s_sel),
      .addr(mem_addr[3:0]),
      .wstrb(mem_wstrb),
      .wdata(mem_wdata),
      .i2s_ready(i2s_ready),
      .i2s_bclk(i2s_bclk),
      .i2s_ws(i2s_ws),
      .i2s_din(i2s_din),
      .i2s_pa_en(i2s_pa_en)
      );

   sram #(.SRAM_ADDR_WIDTH(SRAM_ADDR_WIDTH)) memory
     (
      .clk(clk),
      .reset_n(reset_n),
      .sram_sel(sram_sel),
      .wstrb(mem_wstrb),
      .addr(mem_addr[SRAM_ADDR_WIDTH + 1:0]),
      .sram_data_i(mem_wdata),
      .sram_ready(sram_ready),
      .sram_data_o(sram_data_o)
      );

   tang_leds soc_leds
     (
      .clk(clk),
      .reset_n(reset_n),
      .leds_sel(leds_sel),
      .leds_data_i(mem_wdata[5:0]),
      .we(mem_wstrb[0]),
      .leds_ready(leds_ready),
      .leds_data_o(leds_data_o)
      );

   picorv32
     #(
       .STACKADDR(STACKADDR),
       .PROGADDR_RESET(PROGADDR_RESET),
       .PROGADDR_IRQ(PROGADDR_IRQ),
       .BARREL_SHIFTER(0),
       .COMPRESSED_ISA(0),
       .ENABLE_MUL(0),
       .ENABLE_DIV(0),
       .ENABLE_FAST_MUL(0),
       .ENABLE_IRQ(0),
       .ENABLE_IRQ_QREGS(0)
       ) cpu
       (
        .clk         (clk),
        .resetn      (reset_n),
        .mem_valid   (mem_valid),
        .mem_instr   (mem_instr),
        .mem_ready   (mem_ready),
        .mem_addr    (mem_addr),
        .mem_wdata   (mem_wdata),
        .mem_wstrb   (mem_wstrb),
        .mem_rdata   (mem_rdata),
        .irq         (32'b0)
        );

endmodule // top
